repos:
  # Fix end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - '--fix=lf'

  # Lint and format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]

      # Run the formatter.
      - id: ruff-format

  # Static type-checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.18.1'
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        pass_filenames: false
        entry: bash -c 'mypy -p qfieldcloud_sdk "$@"' --
