site_name: QFieldCloud SDK Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - mkdocs-click

nav:
  - QFieldCloud SDK: index.md
  - CLI: cli.md
